export const jLeagueTeams = [
  {
    label: 'CerezoOsaka',
    name: 'セレッソ大阪',
    league: 'J1リーグ',
    img: '/teamUniform/osaka_s.png',
    stadium: 'ヤンマースタジアム長居',
  },
  {
    label: 'KashimaAntlers',
    name: '鹿島アントラーズ',
    league: 'J1リーグ',
    img: '/teamUniform/kashima.png',
    stadium: 'カシマサッカースタジアム',
  },
  {
    label: 'UrawaRedDiamonds',
    name: '浦和レッズ',
    league: 'J1リーグ',
    img: '/teamUniform/urawa.png',
    stadium: '埼玉スタジアム2002',
  },
  {
    label: 'KashiwaReysol',
    name: '柏レイソル',
    league: 'J1リーグ',
    img: '/teamUniform/kashiwa.png',
    stadium: 'フクダ電子アリーナ',
  },
  {
    label: 'FCTokyo',
    name: 'FC東京',
    league: 'J1リーグ',
    img: '/teamUniform/tokyo.png',
    stadium: '味の素スタジアム',
  },
  {
    label: 'KawasakiFrontale',
    name: '川崎フロンターレ',
    league: 'J1リーグ',
    img: '/teamUniform/kawasaki.png',
    stadium: '等々力陸上競技場',
  },
  {
    label: 'YokohamaFMarinos',
    name: '横浜F・マリノス',
    league: 'J1リーグ',
    img: '/teamUniform/yokohama.png',
    stadium: '日産スタジアム',
  },
  {
    label: 'ShonanBellmare',
    name: '湘南ベルマーレ',
    league: 'J1リーグ',
    img: '/teamUniform/shonan.png',
    stadium: 'Shonan BMW スタジアム平塚',
  },
  {
    label: 'JubiloIwata',
    name: 'ジュビロ磐田',
    league: 'J1リーグ',
    img: '/teamUniform/jbiro.png',
    stadium: 'デンカビッグスワンスタジアム',
  },
  {
    label: 'NagoyaGrampus',
    name: '名古屋グランパス',
    league: 'J1リーグ',
    img: '/teamUniform/nagoya.png',
    stadium: 'パロマ瑞穂スタジアム',
  },
  {
    label: 'KyotoSangaFC',
    name: '京都サンガF.C.',
    league: 'J1リーグ',
    img: '/teamUniform/kyoto.png',
    stadium: '京都市西京極総合運動公園陸上競技場',
  },
  {
    label: 'GambaOsaka',
    name: 'ガンバ大阪',
    league: 'J1リーグ',
    img: '/teamUniform/osaka_g.png',
    stadium: 'パナソニックスタジアム吹田',
  },
  {
    label: 'VisselKobe',
    name: 'ヴィッセル神戸',
    league: 'J1リーグ',
    img: '/teamUniform/kode.png',
    stadium: 'ノエビアスタジアム神戸',
  },
  {
    label: 'SanfrecceHiroshima',
    name: 'サンフレッチェ広島',
    league: 'J1リーグ',
    img: '/teamUniform/hiroshima.png',
    stadium: 'エディオンスタジアム広島',
  },
  {
    label: 'AvispaFukuoka',
    name: 'アビスパ福岡',
    league: 'J1リーグ',
    img: '/teamUniform/fukuoka.png',
    stadium: 'ベストアメニティスタジアム',
  },
  {
    label: 'SaganTosu',
    name: 'サガン鳥栖',
    league: 'J1リーグ',
    img: '/teamUniform/tosu.png',
    stadium: 'ベストアメニティスタジアム',
  },
  {
    label: 'ShimizuS-Pulse',
    name: '清水エスパルス',
    league: 'J1リーグ',
    img: '/teamUniform/shimizu.png',
    stadium: '秋田市八橋陸上競技場',
  },
  {
    label: 'ConsadoleSapporo',
    name: 'コンサドーレ札幌',
    league: 'J1リーグ',
    img: '/teamUniform/sapporo.png',
    stadium: '札幌ドーム',
  },
]
